### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by programmeruser2** [firefish111/gone-fishing#1]
The title is self explanatory.

**Comment by firefish111** [comment]
> The title is self explanatory.

a c version of gone fishing for which I will compile to 16bit dos

**Comment by programmeruser2** [comment]
> > The title is self explanatory.
> 
> a c version of gone fishing for which I will compile to 16bit dos

What is gone fishing?

**Comment by firefish111** [comment]
> > > The title is self explanatory.
> > 
> > 
> > a c version of gone fishing for which I will compile to 16bit dos
> 
> What is gone fishing?

look at the repo titled that you idiot

**Comment by firefish111** [comment]
@programmeruser2 hello

**Comment by programmeruser2** [comment]
This one? https://github.com/shirleytwl/gone-fishing

**Comment by firefish111** [comment]
> This one? https://github.com/shirleytwl/gone-fishing

very smart yes the one under my user nitwit
