### ISSUE TITLE
oh haha

### ISSUE THREAD

**Issue by iop3** [firefish111/gone-fishing#1]
you created a new one so tr1angular wouldn't be one of the contributers lol

**Comment by firefish111** [comment]
how tf did you find out

**Comment by TheQuackyDuck** [comment]
i saw it on my dashboard.

**Comment by TheQuackyDuck** [comment]
cuz i follow u

**Comment by TheQuackyDuck** [comment]
i see everything u do

**Comment by darkdarcool** [comment]
Yea, and this game looks fun!

**Comment by firefish111** [comment]
> Yea, and this game looks fun!

I haven't implemented the higher up rods' loot, not have I done the late game (i.e. using your bait to catch big fish which you can sell to become rich)

**Comment by darkdarcool** [comment]
Yea that’s what I guessed

**Comment by TheQuackyDuck** [comment]
oi im back from my decently awful day trip. yes this game looks fun!

**Comment by firefish111** [comment]
no u

**Comment by darkdarcool** [comment]
?

**Comment by firefish111** [comment]
no u

**Comment by firefish111** [comment]
i was bored at school during break so i made pixel art for every item in game, even though it's s terminal game. I guess the plan is to learn kaboom

**Comment by darkdarcool** [comment]
LOL ok

**Comment by firefish111** [comment]
@darkdarcool paint 3d is a good pixel art tool

**Comment by darkdarcool** [comment]
I just use piskell

**Comment by firefish111** [comment]
I've never heard of that, I may try it but I will always use paint 3d

**Comment by darkdarcool** [comment]
I use it for Minecraft modding when I’m making new assets

https://www.piskelapp.com/

**Comment by darkdarcool** [comment]
Please close

**Comment by darkdarcool** [comment]
Thank you

**Comment by TheQuackyDuck** [comment]
np

**Comment by firefish111** [comment]
e

**Comment by iop3** [comment]
is this a new feature...

**Comment by iop3** [comment]
"close as not planned" wut

**Comment by iop3** [comment]
huh

**Comment by darkdarcool** [comment]
Oh i remember this lmao

**Comment by iop3** [comment]
;)
